/**
 * Career page copy.
 */
import type { ContentEntry } from "./types";

export const CAREER_CONTENT: ContentEntry[] = [
  {
    key: "career.eyebrow",
    page: "career",
    label: "Page eyebrow",
    default: "Career File",
  },
  {
    key: "career.title",
    page: "career",
    label: "Page main heading",
    default: "The path from fixing tickets to owning the budget",
  },
  {
    key: "career.lead",
    page: "career",
    label: "Page lead paragraph",
    default:
      "I did not move around chasing job titles. Each move added one more kind of responsibility: devices, then networks, then people, then budget and technical direction.",
    multiline: true,
  },
  {
    key: "career.stat.tenure",
    page: "career",
    label: "Stat label: total tenure",
    default: "Total tenure",
  },
  {
    key: "career.stat.leadership",
    page: "career",
    label: "Stat label: leadership roles",
    default: "Leadership roles",
  },
  {
    key: "career.stat.peakTeam",
    page: "career",
    label: "Stat label: largest team",
    default: "Largest team",
  },
  {
    key: "career.title.withData",
    page: "career",
    label: "Intro heading when roles exist",
    default: "{years} years from fixing tickets to owning the budget",
    hint: "Token: {years} is the rounded year count.",
  },
  {
    key: "career.stat.tenure.suffix",
    page: "career",
    label: "Stat suffix: tenure counter",
    default: " yrs",
  },
  {
    key: "career.stat.tenure.hint",
    page: "career",
    label: "Stat hint: tenure",
    default: "{months} months since {year}",
    hint: "Tokens: {months}, {year}.",
  },
  {
    key: "career.stat.leadership.value",
    page: "career",
    label: "Stat value: leadership share",
    default: "{led} of {total}",
    hint: "Tokens: {led}, {total}.",
  },
  {
    key: "career.stat.leadership.hint",
    page: "career",
    label: "Stat hint: leadership roles",
    default: "SPV, Lead, and senior technical roles",
  },
  {
    key: "career.stat.peakTeam.suffix",
    page: "career",
    label: "Stat suffix: peak team counter",
    default: " people",
  },
  {
    key: "career.stat.peakTeam.hint",
    page: "career",
    label: "Stat hint: peak team",
    default: "Direct reports, not the whole division",
  },
  {
    key: "career.stat.sectors",
    page: "career",
    label: "Stat label: sectors covered",
    default: "Sectors covered",
  },
  {
    key: "career.chart.tenure.legend.ic",
    page: "career",
    label: "Tenure chart legend: individual contributor",
    default: "Individual contributor",
  },
  {
    key: "career.chart.tenure.legend.lead",
    page: "career",
    label: "Tenure chart legend: leading a team",
    default: "Leading a team",
  },
  {
    key: "career.chart.scope.legend.people",
    page: "career",
    label: "Scope chart legend: leading people",
    default: "Leading people",
  },
  {
    key: "career.chart.scope.legend.technical",
    page: "career",
    label: "Scope chart legend: purely technical",
    default: "Purely technical",
  },
  {
    key: "career.timeline.period.now",
    page: "career",
    label: "Timeline: open-ended role end",
    default: "now",
  },
  {
    key: "career.timeline.badge.current",
    page: "career",
    label: "Timeline badge: running",
    default: "running",
  },
  {
    key: "career.timeline.badge.latest",
    page: "career",
    label: "Timeline badge: latest",
    default: "latest",
  },
  {
    key: "career.chart.tenure.title",
    page: "career",
    label: "Tenure chart title",
    default: "Active roles per year",
  },
  {
    key: "career.chart.tenure.note",
    page: "career",
    label: "Tenure chart note",
    default:
      "Stacked bars separate technical years from leadership years. Watch 2020, the point where I moved into a supervisor role.",
    multiline: true,
  },
  {
    key: "career.chart.scope.title",
    page: "career",
    label: "Scope chart title",
    default: "Time in role against team size",
  },
  {
    key: "career.chart.scope.note",
    page: "career",
    label: "Scope chart note",
    default: "A rust bar means that role led people. A moss bar means it was purely technical.",
    multiline: true,
  },
  {
    key: "career.table.title",
    page: "career",
    label: "Career table heading",
    default: "Compare it yourself, do not take my summary at face value",
  },
  {
    key: "career.shape.eyebrow",
    page: "career",
    label: "Shape section eyebrow",
    default: "Shape",
  },
  {
    key: "career.shape.title",
    page: "career",
    label: "Shape section heading",
    default: "A trajectory, not a list of dates",
  },
  {
    key: "career.shape.description",
    page: "career",
    label: "Shape section description",
    default:
      "Two different angles: one shows when leadership responsibility started to appear, the other compares time in role against the size of the team held.",
    multiline: true,
  },
  {
    key: "career.timeline.eyebrow",
    page: "career",
    label: "Timeline section eyebrow",
    default: "Timeline",
  },
  {
    key: "career.timeline.title",
    page: "career",
    label: "Timeline section heading",
    default: "What actually changed at each stage",
  },
  {
    key: "career.timeline.description",
    page: "career",
    label: "Timeline section description",
    default: "Role summaries, numbers I can stand behind, and the tools I genuinely used.",
    multiline: true,
  },
  {
    key: "career.table.eyebrow",
    page: "career",
    label: "Table section eyebrow",
    default: "Table",
  },
  {
    key: "career.table.description",
    page: "career",
    label: "Table section description",
    default:
      "Filter by job level or sector, then sort by time in role. Everything runs in your browser.",
    multiline: true,
  },

  // ------------------------------------------------------- chart tooltips
  {
    key: "career.chart.tenure.yearTitle",
    page: "career",
    label: "Tenure chart: tooltip title",
    default: "Year {year}",
    hint: "Token: {year}.",
  },
  {
    key: "career.chart.tenure.row.ic",
    page: "career",
    label: "Tenure chart: technical roles label",
    default: "Technical roles",
  },
  {
    key: "career.chart.tenure.row.lead",
    page: "career",
    label: "Tenure chart: leadership roles label",
    default: "Leadership roles",
  },
  {
    key: "career.chart.tenure.row.positions",
    page: "career",
    label: "Tenure chart: positions label",
    default: "Positions",
  },
  {
    key: "career.chart.value.roles",
    page: "career",
    label: "Tenure chart: role count value",
    default: "{count} roles",
    hint: "Token: {count}.",
  },
  {
    key: "career.chart.series.ic",
    page: "career",
    label: "Tenure chart: technical series name",
    default: "Technical roles",
  },
  {
    key: "career.chart.series.lead",
    page: "career",
    label: "Tenure chart: leadership series name",
    default: "Leadership roles",
  },
  {
    key: "career.chart.scope.axis.months",
    page: "career",
    label: "Scope chart: X axis label",
    default: "months in role",
  },
  {
    key: "career.chart.scope.row.company",
    page: "career",
    label: "Scope chart: company label",
    default: "Company",
  },
  {
    key: "career.chart.scope.row.duration",
    page: "career",
    label: "Scope chart: duration label",
    default: "Duration",
  },
  {
    key: "career.chart.scope.row.team",
    page: "career",
    label: "Scope chart: team label",
    default: "Team",
  },
  {
    key: "career.chart.value.people",
    page: "career",
    label: "Scope chart: team size value",
    default: "{count} people",
    hint: "Token: {count}.",
  },
  {
    key: "career.chart.value.noReports",
    page: "career",
    label: "Scope chart: empty team value",
    default: "no direct reports",
  },

  // ------------------------------------------------------ table chrome
  {
    key: "career.table.col.title",
    page: "career",
    label: "Table column: position",
    default: "Position",
  },
  {
    key: "career.table.col.sector",
    page: "career",
    label: "Table column: sector",
    default: "Sector",
  },
  {
    key: "career.table.col.level",
    page: "career",
    label: "Table column: level",
    default: "Level",
  },
  {
    key: "career.table.col.period",
    page: "career",
    label: "Table column: period",
    default: "Period",
  },
  {
    key: "career.table.col.duration",
    page: "career",
    label: "Table column: duration",
    default: "Duration",
  },
  {
    key: "career.table.col.team",
    page: "career",
    label: "Table column: team",
    default: "Team",
  },
  {
    key: "career.table.col.location",
    page: "career",
    label: "Table column: location",
    default: "Location",
  },
  {
    key: "career.table.col.stack",
    page: "career",
    label: "Table column: working stack",
    default: "Working stack",
  },
  {
    key: "career.table.period.to",
    page: "career",
    label: "Table: period separator",
    default: " to ",
    hint: "Printed between the start and the end date.",
  },
  {
    key: "career.table.period.now",
    page: "career",
    label: "Table: current role end date",
    default: "now",
    hint: "Printed when a role has no end date.",
  },
  {
    key: "career.table.team.value",
    page: "career",
    label: "Table: team size value",
    default: "{count} people",
    hint: "Token: {count}.",
  },
  {
    key: "career.table.team.none",
    page: "career",
    label: "Table: empty team value",
    default: "no reports",
  },
  {
    key: "career.table.duration.title",
    page: "career",
    label: "Table: duration tooltip",
    default: "{count} months",
    hint: "Token: {count}. Shown as a tooltip on the duration cell.",
  },
  {
    key: "career.table.searchHint",
    page: "career",
    label: "Table: search placeholder",
    default: "Search position, company, or working stack",
  },
  {
    key: "career.table.empty",
    page: "career",
    label: "Table: empty message",
    default: "No role history matches this filter.",
  },
  {
    key: "career.table.facet.level",
    page: "career",
    label: "Table filter label: level",
    default: "Level",
  },
  {
    key: "career.table.facet.sector",
    page: "career",
    label: "Table filter label: sector",
    default: "Sector",
  },
  {
    key: "career.cta.eyebrow",
    page: "career",
    label: "CTA eyebrow",
    default: "continued",
  },
  {
    key: "career.cta.body",
    page: "career",
    label: "CTA paragraph",
    default:
      "This history is only the frame. The evidence of the work lives on the projects and skills pages.",
    multiline: true,
  },
  {
    key: "career.cta.button.projects",
    page: "career",
    label: "CTA button: projects",
    default: "View projects",
  },
  {
    key: "career.cta.button.skills",
    page: "career",
    label: "CTA button: skills",
    default: "Check the skills",
  },
];
