/**
 * Contact page copy.
 */
import type { ContentEntry } from "./types";

export const CONTACT_CONTENT: ContentEntry[] = [
  {
    key: "contact.eyebrow",
    page: "contact",
    label: "Page eyebrow",
    default: "Contact File",
  },
  {
    key: "contact.title",
    page: "contact",
    label: "Page main heading",
    default: "Send a specific question, and I will answer specifically",
  },
  {
    key: "contact.lead",
    page: "contact",
    label: "Page lead paragraph",
    default:
      "I prefer questions that name the real situation, the number of people, and the budget constraint. Questions like that I can answer from experience, not from generic theory.",
    multiline: true,
  },
  {
    key: "contact.stat.response",
    page: "contact",
    label: "Stat label: response time",
    default: "Response time",
  },
  {
    key: "contact.stat.timezone",
    page: "contact",
    label: "Stat label: time zone",
    default: "Time zone",
  },
  {
    key: "contact.stat.channels",
    page: "contact",
    label: "Stat label: direct channels",
    default: "Direct channels",
  },
  {
    key: "contact.stat.status",
    page: "contact",
    label: "Stat label: status",
    default: "Status",
  },
  {
    key: "contact.stat.response.value",
    page: "contact",
    label: "Stat value: response time",
    default: "1 business day",
  },
  {
    key: "contact.stat.response.hint",
    page: "contact",
    label: "Stat hint: response time",
    default: "Usually faster on weekdays",
  },
  {
    key: "contact.stat.timezone.hint",
    page: "contact",
    label: "Stat hint: time zone",
    default: "I work from {location}",
    hint: "Token: {location} is the profile location.",
  },
  {
    key: "contact.stat.channels.hint",
    page: "contact",
    label: "Stat hint: direct channels",
    default: "{names}",
    hint: "Token: {names} is the list of channel names, already joined.",
  },
  {
    key: "contact.stat.status.value",
    page: "contact",
    label: "Stat value: status",
    default: "{availability}",
    hint: "Token: {availability} is the profile availability.",
  },
  {
    key: "contact.stat.status.hint",
    page: "contact",
    label: "Stat hint: status",
    default: "Open to {roles}",
    hint: "Token: {roles} is the role scope the owner is open to.",
  },
  {
    key: "contact.form.eyebrow",
    page: "contact",
    label: "Form section eyebrow",
    default: "Form",
  },
  {
    key: "contact.form.field.name.label",
    page: "contact",
    label: "Field label: name",
    default: "Name",
  },
  {
    key: "contact.form.field.name.placeholder",
    page: "contact",
    label: "Field placeholder: name",
    default: "Full name",
  },
  {
    key: "contact.form.field.email.label",
    page: "contact",
    label: "Field label: email",
    default: "Email",
  },
  {
    key: "contact.form.field.email.placeholder",
    page: "contact",
    label: "Field placeholder: email",
    default: "name@company.com",
  },
  {
    key: "contact.form.field.topic.label",
    page: "contact",
    label: "Field label: topic",
    default: "Topic",
  },
  {
    key: "contact.form.field.topic.placeholder",
    page: "contact",
    label: "Field placeholder: topic",
    default: "Choose a topic",
  },
  {
    key: "contact.form.field.message.label",
    page: "contact",
    label: "Field label: message",
    default: "Message",
  },
  {
    key: "contact.form.field.message.placeholder",
    page: "contact",
    label: "Field placeholder: message",
    default:
      "Describe the situation: how many people are on the team, which systems are in use, and which constraint hurts the most.",
    multiline: true,
  },
  {
    key: "contact.form.topic.option.1",
    page: "contact",
    label: "Topic option 1",
    default: "IT Lead or SPV role",
  },
  {
    key: "contact.form.topic.option.2",
    page: "contact",
    label: "Topic option 2",
    default: "Infrastructure consulting",
  },
  {
    key: "contact.form.topic.option.3",
    page: "contact",
    label: "Topic option 3",
    default: "Operational readiness",
  },
  {
    key: "contact.form.topic.option.4",
    page: "contact",
    label: "Topic option 4",
    default: "Collaboration or mentoring",
  },
  {
    key: "contact.form.topic.option.5",
    page: "contact",
    label: "Topic option 5",
    default: "Questions about the portfolio",
  },
  {
    key: "contact.form.error.name",
    page: "contact",
    label: "Validation error: name",
    default: "Write your name, at least two characters.",
  },
  {
    key: "contact.form.error.email",
    page: "contact",
    label: "Validation error: email",
    default: "That email address is not shaped correctly.",
  },
  {
    key: "contact.form.error.message",
    page: "contact",
    label: "Validation error: message too short",
    default: "{count} more characters to go.",
    hint: "Token: {count} is the number of characters still missing.",
  },
  {
    key: "contact.form.error.summary",
    page: "contact",
    label: "Validation error count",
    default: "{count} fields need fixing",
    hint: "Token: {count} is the number of invalid fields.",
  },
  {
    key: "contact.form.counter",
    page: "contact",
    label: "Character counter",
    default: "{count} characters",
    hint: "Token: {count} is the current message length.",
  },
  {
    key: "contact.form.length.label",
    page: "contact",
    label: "Message length progress label",
    default: "Message length",
    hint: "Screen reader label for the progress bar under the message field.",
  },
  {
    key: "contact.form.hint.ready",
    page: "contact",
    label: "Message hint when ready",
    default: "The message is long enough for me to answer usefully.",
  },
  {
    key: "contact.form.hint.tooShort",
    page: "contact",
    label: "Message hint when too short",
    default: "At least {count} characters so I understand the context.",
    hint: "Token: {count} is the minimum message length.",
  },
  {
    key: "contact.form.submit",
    page: "contact",
    label: "Submit button",
    default: "Send message",
  },
  {
    key: "contact.form.submit.sending",
    page: "contact",
    label: "Submit button while sending",
    default: "Sending",
  },
  {
    key: "contact.form.clear",
    page: "contact",
    label: "Clear form button",
    default: "Clear",
  },
  {
    key: "contact.form.copy",
    page: "contact",
    label: "Copy message button",
    default: "Copy message",
  },
  {
    key: "contact.form.copy.copied",
    page: "contact",
    label: "Copy message button after copying",
    default: "Copied",
  },
  {
    key: "contact.form.copy.placeholder.name",
    page: "contact",
    label: "Copy placeholder: name not filled",
    default: "(not filled in yet)",
  },
  {
    key: "contact.form.preview.name",
    page: "contact",
    label: "Copy preview: name row",
    default: "Name: {value}",
  },
  {
    key: "contact.form.preview.email",
    page: "contact",
    label: "Copy preview: email row",
    default: "Email: {value}",
  },
  {
    key: "contact.form.preview.topic",
    page: "contact",
    label: "Copy preview: topic row",
    default: "Topic: {value}",
  },
  {
    key: "contact.form.error.send",
    page: "contact",
    label: "Send failure fallback message",
    default: "The message could not be delivered.",
  },
  {
    key: "contact.form.sent.title",
    page: "contact",
    label: "Sent banner eyebrow",
    default: "message received",
  },
  {
    key: "contact.form.sent.body",
    page: "contact",
    label: "Sent banner paragraph",
    default:
      "The message reached {email}. Expect an answer within one business day, usually faster on weekdays.",
    multiline: true,
    hint: "Token: {email} is the recipient address.",
  },
  {
    key: "contact.form.failed.title",
    page: "contact",
    label: "Failed banner eyebrow",
    default: "not delivered",
  },
  {
    key: "contact.form.failed.body",
    page: "contact",
    label: "Failed banner paragraph",
    default:
      "{error} Nothing was lost from this page, so you can press send again or copy the message and use a direct channel.",
    multiline: true,
    hint: "Token: {error} is the reason reported by the sender.",
  },
  {
    key: "contact.sidebar.answer.title",
    page: "contact",
    label: "Sidebar heading: what I will answer",
    default: "what I will answer",
  },
  {
    key: "contact.sidebar.answer.item.1",
    page: "contact",
    label: "Sidebar item: answer 1",
    default: "Technical questions that name the system, the scale, and the deadline.",
  },
  {
    key: "contact.sidebar.answer.item.2",
    page: "contact",
    label: "Sidebar item: answer 2",
    default: "Second opinions on infrastructure design or IT budgeting.",
  },
  {
    key: "contact.sidebar.answer.item.3",
    page: "contact",
    label: "Sidebar item: answer 3",
    default: "Interview invitations for a lead or supervisor role.",
  },
  {
    key: "contact.sidebar.answer.item.4",
    page: "contact",
    label: "Sidebar item: answer 4",
    default: "Requests for reading material, not requests to do someone else's homework.",
  },
  {
    key: "contact.sidebar.promise.title",
    page: "contact",
    label: "Sidebar heading: what I do not promise",
    default: "what I do not promise",
  },
  {
    key: "contact.sidebar.promise.body",
    page: "contact",
    label: "Sidebar paragraph: what I do not promise",
    default:
      "I do not take on full-time freelance work, and I will not recommend tools without knowing the problem you are actually facing.",
    multiline: true,
  },
  {
    key: "contact.sidebar.note.title",
    page: "contact",
    label: "Sidebar heading: technical note",
    default: "technical note",
  },
  {
    key: "contact.sidebar.note.body",
    page: "contact",
    label: "Sidebar paragraph: technical note",
    default:
      "Press send and the message travels to a private inbox. It is stored first, then emailed, so nothing is lost if the delivery service stumbles. No account, no tracking pixel, no third party reading along.",
    multiline: true,
  },
  {
    key: "contact.channels.badge.open",
    page: "contact",
    label: "Channels panel badge: availability",
    default: "open to discussion",
  },
  {
    key: "contact.channels.badge.reply",
    page: "contact",
    label: "Channels panel badge: reply time",
    default: "replies within 1 business day",
  },
  {
    key: "contact.cta.button.projects",
    page: "contact",
    label: "Closing CTA button: projects",
    default: "Open the project file",
  },
  {
    key: "contact.cta.button.home",
    page: "contact",
    label: "Closing CTA button: home",
    default: "Back to home",
  },
  {
    key: "contact.form.title",
    page: "contact",
    label: "Form section heading",
    default: "Write your message and send it straight from this page",
  },
  {
    key: "contact.form.description",
    page: "contact",
    label: "Form section description",
    default:
      "The message is stored first and emailed second, so a delivery hiccup never loses your words. No account, no tracking pixel, and no third party reading along.",
    multiline: true,
  },
  {
    key: "contact.channels.title",
    page: "contact",
    label: "Direct channels panel heading",
    default: "direct channels",
  },
  {
    key: "contact.cta.eyebrow",
    page: "contact",
    label: "Closing CTA eyebrow",
    default: "before you write",
  },
  {
    key: "contact.cta.body",
    page: "contact",
    label: "Closing CTA paragraph",
    default:
      "If you have just opened this site, start with the project file. That is where the way I work shows up, not only the end result.",
    multiline: true,
  },
];
