/**
 * Credentials page copy.
 */
import type { ContentEntry } from "./types";

export const CREDENTIALS_CONTENT: ContentEntry[] = [
  {
    key: "credentials.eyebrow",
    page: "credentials",
    label: "Page eyebrow",
    default: "Credentials File",
  },
  {
    key: "credentials.title",
    page: "credentials",
    label: "Page main heading",
    default: "Certifications and formal qualifications",
  },
  {
    key: "credentials.lead",
    page: "credentials",
    label: "Page lead paragraph",
    default:
      "A certificate is not proof of skill, only proof that I passed a specific exam once. That is why I show the expired ones and the ones being renewed, not just the active ones.",
    multiline: true,
  },
  {
    key: "credentials.stat.active",
    page: "credentials",
    label: "Stat label: active certs",
    default: "Active certificates",
  },
  {
    key: "credentials.stat.renewal",
    page: "credentials",
    label: "Stat label: needs renewal",
    default: "Needs renewal",
  },
  {
    key: "credentials.stat.domains",
    page: "credentials",
    label: "Stat label: domains covered",
    default: "Domains covered",
  },
  {
    key: "credentials.stat.investment",
    page: "credentials",
    label: "Stat label: total investment",
    default: "Total invested",
  },
  {
    key: "credentials.intro.index",
    page: "credentials",
    label: "Intro index marker",
    default: "05",
  },
  {
    key: "credentials.stat.active.hint",
    page: "credentials",
    label: "Stat hint: active credentials",
    default: "{count} of them have no expiry",
    hint: "Token: {count}.",
  },
  {
    key: "credentials.stat.renewal.hint",
    page: "credentials",
    label: "Stat hint: renewals",
    default: "{count} already past their expiry",
    hint: "Token: {count}.",
  },
  {
    key: "credentials.stat.renewal.suffix",
    page: "credentials",
    label: "Stat suffix: renewals counter",
    default: " items",
  },
  {
    key: "credentials.stat.investment.hint",
    page: "credentials",
    label: "Stat hint: investment",
    default: "Out of my own pocket since 2018",
  },
  {
    key: "credentials.stat.investment.prefix",
    page: "credentials",
    label: "Stat prefix: investment counter",
    default: "Rp ",
  },
  {
    key: "credentials.stat.investment.suffix",
    page: "credentials",
    label: "Stat suffix: investment counter",
    default: "m",
  },
  {
    key: "credentials.validity.index",
    page: "credentials",
    label: "Validity section index marker",
    default: "01",
  },
  {
    key: "credentials.validity.description",
    page: "credentials",
    label: "Validity section description",
    default:
      "This chart answers the question that comes up most in interviews: which ones are still valid, which ones need handling, and which ones have already lapsed.",
    multiline: true,
  },
  {
    key: "credentials.validity.chart.title",
    page: "credentials",
    label: "Validity chart title",
    default: "Remaining validity per certificate",
  },
  {
    key: "credentials.validity.chart.note",
    page: "credentials",
    label: "Validity chart note",
    default:
      "Measured in months. A negative value means it has expired. Certificates with no expiry are drawn as a full bar.",
    multiline: true,
  },
  {
    key: "credentials.validity.tip.issuer",
    page: "credentials",
    label: "Validity tooltip: issuer",
    default: "Issuer",
  },
  {
    key: "credentials.validity.tip.domain",
    page: "credentials",
    label: "Validity tooltip: domain",
    default: "Domain",
  },
  {
    key: "credentials.validity.tip.validUntil",
    page: "credentials",
    label: "Validity tooltip: valid until",
    default: "Valid until",
  },
  {
    key: "credentials.validity.tip.noExpiry",
    page: "credentials",
    label: "Validity tooltip: no expiry value",
    default: "no expiry",
  },
  {
    key: "credentials.validity.tip.status",
    page: "credentials",
    label: "Validity tooltip: status",
    default: "Status",
  },
  {
    key: "credentials.validity.tip.permanent",
    page: "credentials",
    label: "Validity tooltip: permanent value",
    default: "permanent",
  },
  {
    key: "credentials.validity.tip.monthsLeft",
    page: "credentials",
    label: "Validity tooltip: months left",
    default: "{count} months left",
    hint: "Token: {count}.",
  },
  {
    key: "credentials.validity.tip.monthsOverdue",
    page: "credentials",
    label: "Validity tooltip: months overdue",
    default: "{count} months overdue",
    hint: "Token: {count}.",
  },
  {
    key: "credentials.validity.stat.longest",
    page: "credentials",
    label: "Validity side stat: longest remaining",
    default: "Longest remaining",
  },
  {
    key: "credentials.validity.stat.soonest",
    page: "credentials",
    label: "Validity side stat: soonest expiry",
    default: "Soonest expiry",
  },
  {
    key: "credentials.validity.stat.lapsed",
    page: "credentials",
    label: "Validity side stat: already lapsed",
    default: "Already lapsed",
  },
  {
    key: "credentials.validity.stat.lapsed.hint",
    page: "credentials",
    label: "Validity side stat hint: lapsed",
    default: "Kept visible on purpose, not deleted",
  },
  {
    key: "credentials.validity.agenda.title",
    page: "credentials",
    label: "Renewal agenda heading",
    default: "Renewal agenda",
  },
  {
    key: "credentials.validity.agenda.note",
    page: "credentials",
    label: "Renewal agenda note",
    default: "next 12 months",
  },
  {
    key: "credentials.validity.agenda.empty",
    page: "credentials",
    label: "Renewal agenda empty state",
    default: "No certificate comes due within the next twelve months.",
  },
  {
    key: "credentials.validity.agenda.midRenewal",
    page: "credentials",
    label: "Renewal agenda mid-renewal note",
    default: "{count} certificates are mid-renewal: {names}.",
    hint: "Tokens: {count} and {names}.",
  },
  {
    key: "credentials.validity.rhythm.title",
    page: "credentials",
    label: "Issuance rhythm heading",
    default: "Issuance rhythm",
  },
  {
    key: "credentials.validity.rhythm.note",
    page: "credentials",
    label: "Issuance rhythm note",
    default: "Certificates per year of issue",
  },
  {
    key: "credentials.composition.share",
    page: "credentials",
    label: "Domain card: share of total",
    default: "{count} of {total}",
    hint: "Tokens: {count} and {total}.",
  },
  {
    key: "credentials.composition.share.aria",
    page: "credentials",
    label: "Domain share bar label",
    default: "{count} certificates in {domain}",
    hint: "Tokens: {count} and {domain}.",
  },
  {
    key: "credentials.composition.cost",
    page: "credentials",
    label: "Domain card: exam fees",
    default: "Rp {amount}m in exam fees",
    hint: "Token: {amount}.",
  },
  {
    key: "credentials.composition.gap.eyebrow",
    page: "credentials",
    label: "Gap panel eyebrow",
    default: "what is missing here",
  },
  {
    key: "credentials.composition.gap.title",
    page: "credentials",
    label: "Gap panel heading",
    default: "No AI governance or advanced cloud architecture certificates",
  },
  {
    key: "credentials.composition.gap.body",
    page: "credentials",
    label: "Gap panel paragraph",
    default:
      "I have not taken either, and I would rather say so than pad the list with short courses. What I have is experience running production systems across branches, not a collection of badges.",
    multiline: true,
  },
  {
    key: "credentials.composition.gap.item.1",
    page: "credentials",
    label: "Gap bullet: still valid",
    default: "{count} certificates still valid",
    hint: "Token: {count}.",
  },
  {
    key: "credentials.composition.gap.item.2",
    page: "credentials",
    label: "Gap bullet: expired but shown",
    default: "{count} expired and still shown here",
    hint: "Token: {count}.",
  },
  {
    key: "credentials.composition.gap.item.3",
    page: "credentials",
    label: "Gap bullet: verifiable IDs",
    default: "Every credential ID can be checked independently",
  },
  {
    key: "credentials.cta.eyebrow",
    page: "credentials",
    label: "CTA eyebrow",
    default: "continued",
  },
  {
    key: "credentials.cta.body",
    page: "credentials",
    label: "CTA paragraph",
    default:
      "A certificate is only the entry ticket. What carries the daily work lives on the skills page, complete with the level of evidence behind it.",
    multiline: true,
  },
  {
    key: "credentials.cta.invested",
    page: "credentials",
    label: "CTA investment note",
    default: "Rp {amount}m invested in {count} {noun}",
    hint: "Tokens: {amount}, {count}, {noun} (singular/plural credential).",
  },
  {
    key: "credentials.cta.noun.one",
    page: "credentials",
    label: "CTA investment note: singular noun",
    default: "credential",
  },
  {
    key: "credentials.cta.noun.many",
    page: "credentials",
    label: "CTA investment note: plural noun",
    default: "credentials",
  },
  {
    key: "credentials.cta.button.skills",
    page: "credentials",
    label: "CTA button: skills",
    default: "Check the skills",
  },
  {
    key: "credentials.cta.button.contact",
    page: "credentials",
    label: "CTA button: contact",
    default: "Ask about credentials",
  },
  {
    key: "credentials.related.button",
    page: "credentials",
    label: "Table section action button",
    default: "Related skills",
  },
  {
    key: "credentials.composition.index",
    page: "credentials",
    label: "Composition section index marker",
    default: "02",
  },
  {
    key: "credentials.composition.description",
    page: "credentials",
    label: "Composition section description",
    default:
      "This spread is deliberately uneven. Security and infrastructure dominate because those two are the most common source of operational failure everywhere I have worked.",
    multiline: true,
  },
  {
    key: "credentials.composition.chart.title",
    page: "credentials",
    label: "Composition chart title",
    default: "Certificates per domain",
  },
  {
    key: "credentials.composition.chart.note",
    page: "credentials",
    label: "Composition chart note",
    default: "Counted by domain, not by vendor. One certificate belongs to one domain only.",
  },
  {
    key: "credentials.composition.point.coverage",
    page: "credentials",
    label: "Composition bullet: coverage",
    default: "Coverage over depth",
  },
  {
    key: "credentials.composition.point.coverage.body",
    page: "credentials",
    label: "Composition bullet body: coverage",
    default: "A few domains reached properly, instead of a long list of one-off badges.",
  },
  {
    key: "credentials.composition.point.renewal",
    page: "credentials",
    label: "Composition bullet: renewal load",
    default: "Renewal load",
  },
  {
    key: "credentials.composition.point.renewal.body",
    page: "credentials",
    label: "Composition bullet body: renewal load",
    default: "Every certificate here has a real renewal date attached to it, tracked in the table below.",
  },
  {
    key: "credentials.table.index",
    page: "credentials",
    label: "Table section index marker",
    default: "03",
  },
  {
    key: "credentials.validity.eyebrow",
    page: "credentials",
    label: "Validity section eyebrow",
    default: "Validity",
  },
  {
    key: "credentials.validity.title",
    page: "credentials",
    label: "Validity section heading",
    default: "How much longer each credential holds up",
  },
  {
    key: "credentials.composition.eyebrow",
    page: "credentials",
    label: "Composition section eyebrow",
    default: "Composition",
  },
  {
    key: "credentials.composition.title",
    page: "credentials",
    label: "Composition section heading",
    default: "The domains I went after, and what they mean for a lead role",
  },
  {
    key: "credentials.table.eyebrow",
    page: "credentials",
    label: "Table section eyebrow",
    default: "Full file",
  },
  {
    key: "credentials.table.title",
    page: "credentials",
    label: "Table section heading",
    default: "Every credential, filterable and checkable",
  },
  {
    key: "credentials.table.description",
    page: "credentials",
    label: "Table section description",
    default:
      "Use the search to find a specific issuer, or filter by domain and status. The credential ID column can be copied for verification.",
    multiline: true,
  },

  // ------------------------------------------------------ table chrome
  {
    key: "credentials.table.col.name",
    page: "credentials",
    label: "Table column: certification",
    default: "Certification",
  },
  {
    key: "credentials.table.col.domain",
    page: "credentials",
    label: "Table column: domain",
    default: "Domain",
  },
  {
    key: "credentials.table.col.issuer",
    page: "credentials",
    label: "Table column: issuer",
    default: "Issuer",
  },
  {
    key: "credentials.table.col.issued",
    page: "credentials",
    label: "Table column: issued",
    default: "Issued",
  },
  {
    key: "credentials.table.col.expires",
    page: "credentials",
    label: "Table column: valid until",
    default: "Valid until",
  },
  {
    key: "credentials.table.col.status",
    page: "credentials",
    label: "Table column: status",
    default: "Status",
  },
  {
    key: "credentials.table.col.credentialId",
    page: "credentials",
    label: "Table column: credential ID",
    default: "Credential ID",
  },
  {
    key: "credentials.table.col.cost",
    page: "credentials",
    label: "Table column: cost",
    default: "Cost",
  },
  {
    key: "credentials.table.value.noExpiry",
    page: "credentials",
    label: "Table: empty date value",
    default: "no expiry",
    hint: "Printed in a date cell when a credential has no date.",
  },
  {
    key: "credentials.table.value.cost",
    page: "credentials",
    label: "Table: cost value",
    default: "Rp {amount}m",
    hint: "Token: {amount}, formatted with one decimal. The m stands for millions.",
  },
  {
    key: "credentials.table.expiry.title",
    page: "credentials",
    label: "Table: expiry warning tooltip",
    default: "Less than {count} months left",
    hint: "Token: {count}. Tooltip on the warning icon next to the expiry date.",
  },
  {
    key: "credentials.table.expiry.short",
    page: "credentials",
    label: "Table: expiry warning badge",
    default: "{count} mo",
    hint: "Token: {count}. The small badge next to the expiry date.",
  },
  {
    key: "credentials.table.searchHint",
    page: "credentials",
    label: "Table: search placeholder",
    default: "Search certification, issuer, or credential ID",
  },
  {
    key: "credentials.table.footnote",
    page: "credentials",
    label: "Table: footnote",
    default: "Credential IDs can be copied for verification",
  },
  {
    key: "credentials.table.facet.domain",
    page: "credentials",
    label: "Table filter label: domain",
    default: "Domain",
  },
  {
    key: "credentials.table.facet.status",
    page: "credentials",
    label: "Table filter label: status",
    default: "Status",
  },
  {
    key: "credentials.table.facet.issuer",
    page: "credentials",
    label: "Table filter label: issuer",
    default: "Issuer",
  },
];
