/**
 * Projects page copy.
 */
import type { ContentEntry } from "./types";

export const PROJECTS_CONTENT: ContentEntry[] = [
  {
    key: "projects.eyebrow",
    page: "projects",
    label: "Page eyebrow",
    default: "Project File",
  },
  {
    key: "projects.title",
    page: "projects",
    label: "Page main heading",
    default: "Twelve traceable pieces of work, not just a list of tools",
  },
  {
    key: "projects.lead",
    page: "projects",
    label: "Page lead paragraph",
    default:
      "Every project below has a budget, a duration, a team size, and an impact score. I kept the small numbers in too, because they show the pattern: valuable work usually runs long.",
    multiline: true,
  },
  {
    key: "projects.stat.budget",
    page: "projects",
    label: "Stat label: budget managed",
    default: "Budget managed",
  },
  {
    key: "projects.stat.running",
    page: "projects",
    label: "Stat label: projects running",
    default: "Projects running",
  },
  {
    key: "projects.stat.sites",
    page: "projects",
    label: "Stat label: reaching many sites",
    default: "Reaching many sites",
  },
  {
    key: "projects.stat.impact",
    page: "projects",
    label: "Stat label: average impact",
    default: "Average impact",
  },
  {
    key: "projects.quickread.eyebrow",
    page: "projects",
    label: "Quick read eyebrow",
    default: "Quick read",
  },
  {
    key: "projects.quickread.title",
    page: "projects",
    label: "Quick read heading",
    default: "How projects spread across kind, time, and budget size",
  },
  {
    key: "projects.quickread.description",
    page: "projects",
    label: "Quick read description",
    default:
      "The bubble map shows when the work happened and how much impact it had. Bubble size is the impact score, colour is the kind of work.",
    multiline: true,
  },
  {
    key: "projects.featured.eyebrow",
    page: "projects",
    label: "Featured section eyebrow",
    default: "Featured",
  },
  {
    key: "projects.featured.title",
    page: "projects",
    label: "Featured section heading",
    default: "Four projects that explain how I work",
  },
  {
    key: "projects.featured.description",
    page: "projects",
    label: "Featured section description",
    default:
      "Chosen not because they had the biggest budgets, but because they represent the thinking I repeat across many other pieces of work.",
    multiline: true,
  },
  {
    key: "projects.composition.eyebrow",
    page: "projects",
    label: "Composition section eyebrow",
    default: "Composition",
  },
  {
    key: "projects.composition.title",
    page: "projects",
    label: "Composition section heading",
    default: "Where the budget and the attention actually went",
  },
  {
    key: "projects.table.eyebrow",
    page: "projects",
    label: "Table section eyebrow",
    default: "Full file",
  },
  {
    key: "projects.table.title",
    page: "projects",
    label: "Table section heading",
    default: "Every project in one filterable table",
  },
  {
    key: "projects.table.description",
    page: "projects",
    label: "Table section description",
    default:
      "Search, sort by column, or filter by kind, status, and year. Everything runs in your browser.",
    multiline: true,
  },

  // ------------------------------------------------------------ table chrome
  {
    key: "projects.table.col.name",
    page: "projects",
    label: "Table column: project name",
    default: "Project",
  },
  {
    key: "projects.table.col.kind",
    page: "projects",
    label: "Table column: kind of work",
    default: "Kind",
  },
  {
    key: "projects.table.col.status",
    page: "projects",
    label: "Table column: status",
    default: "Status",
  },
  {
    key: "projects.table.col.year",
    page: "projects",
    label: "Table column: year",
    default: "Year",
  },
  {
    key: "projects.table.col.role",
    page: "projects",
    label: "Table column: role",
    default: "Role",
  },
  {
    key: "projects.table.col.budget",
    page: "projects",
    label: "Table column: budget",
    default: "Budget",
  },
  {
    key: "projects.table.col.impact",
    page: "projects",
    label: "Table column: impact",
    default: "Impact",
  },
  {
    key: "projects.table.col.stack",
    page: "projects",
    label: "Table column: technology",
    default: "Technology",
  },
  {
    key: "projects.table.featured",
    page: "projects",
    label: "Table: featured marker",
    default: "featured",
    hint: "The small uppercase tag under a featured project name.",
  },
  {
    key: "projects.table.budgetValue",
    page: "projects",
    label: "Table: budget cell value",
    default: "Rp {amount}m",
    hint: "Token: {amount}, already formatted with thousand separators.",
  },
  {
    key: "projects.table.budgetTitle",
    page: "projects",
    label: "Table: budget cell tooltip",
    default: "Rp {amount} million",
    hint: "Token: {amount}. Shown on hover over the budget cell.",
  },
  {
    key: "projects.table.searchHint",
    page: "projects",
    label: "Table: search placeholder",
    default: "Search project, role, or technology",
  },
  {
    key: "projects.table.footnote",
    page: "projects",
    label: "Table: footnote",
    default: "All filters run client side",
  },
  {
    key: "projects.table.facet.kind",
    page: "projects",
    label: "Table filter name: kind",
    default: "Kind",
  },
  {
    key: "projects.table.facet.status",
    page: "projects",
    label: "Table filter name: status",
    default: "Status",
  },
  {
    key: "projects.table.facet.year",
    page: "projects",
    label: "Table filter name: year",
    default: "Year",
  },

  // -------------------------------------------------------- chart tooltips
  {
    key: "projects.chart.row.role",
    page: "projects",
    label: "Chart tooltip label: role",
    default: "Role",
  },
  {
    key: "projects.chart.row.status",
    page: "projects",
    label: "Chart tooltip label: status",
    default: "Status",
  },
  {
    key: "projects.chart.row.impact",
    page: "projects",
    label: "Chart tooltip label: impact",
    default: "Impact",
  },
  {
    key: "projects.chart.row.budget",
    page: "projects",
    label: "Chart tooltip label: budget",
    default: "Budget",
  },
  {
    key: "projects.chart.row.duration",
    page: "projects",
    label: "Chart tooltip label: duration",
    default: "Duration",
  },
  {
    key: "projects.chart.row.totalBudget",
    page: "projects",
    label: "Chart tooltip label: total budget",
    default: "Total budget",
  },
  {
    key: "projects.chart.row.avgImpact",
    page: "projects",
    label: "Chart tooltip label: average impact",
    default: "Average impact",
  },
  {
    key: "projects.chart.row.projectCount",
    page: "projects",
    label: "Chart tooltip label: project count",
    default: "Project count",
  },
  {
    key: "projects.chart.row.teamSize",
    page: "projects",
    label: "Chart tooltip label: team size",
    default: "Team size",
  },
  {
    key: "projects.chart.value.impactScore",
    page: "projects",
    label: "Chart tooltip value: impact score",
    default: "{value}/100",
    hint: "Tokens: {value}.",
  },
  {
    key: "projects.chart.value.budget",
    page: "projects",
    label: "Chart tooltip value: budget",
    default: "Rp {amount}m",
    hint: "Tokens: {amount}, already formatted with thousand separators.",
  },
  {
    key: "projects.chart.value.budgetShort",
    page: "projects",
    label: "Chart tooltip value: budget, short form",
    default: "${amount}k",
    hint: "Tokens: {amount}. Used by the bubble chart tooltip.",
  },
  {
    key: "projects.chart.value.internal",
    page: "projects",
    label: "Chart tooltip value: no budget",
    default: "internal",
    hint: "Shown when a project has no direct budget figure.",
  },
  {
    key: "projects.chart.value.months",
    page: "projects",
    label: "Chart tooltip value: duration in months",
    default: "{count} months",
    hint: "Tokens: {count}.",
  },
  {
    key: "projects.chart.value.people",
    page: "projects",
    label: "Chart tooltip value: number of people",
    default: "{count} people",
    hint: "Tokens: {count}.",
  },
  {
    key: "projects.chart.value.yearTitle",
    page: "projects",
    label: "Chart tooltip title: year",
    default: "Year {year}",
    hint: "Tokens: {year}.",
  },
  {
    key: "projects.chart.axis.year",
    page: "projects",
    label: "Chart axis name: year",
    default: "Year",
  },
  {
    key: "projects.chart.axis.budget",
    page: "projects",
    label: "Chart axis name: budget",
    default: "Budget (IDR millions)",
  },
  {
    key: "projects.chart.axis.impact",
    page: "projects",
    label: "Chart axis name: impact score",
    default: "Impact score",
  },

  // ------------------------------------------------------ page furniture
  {
    key: "projects.intro.index",
    page: "projects",
    label: "Page intro number",
    default: "03",
    hint: "The number printed on the page intro above the title.",
  },
  {
    key: "projects.section.map.index",
    page: "projects",
    label: "Section number: project map",
    default: "01",
    hint: "The large faded numeral beside the section heading.",
  },
  {
    key: "projects.section.featured.index",
    page: "projects",
    label: "Section number: featured work",
    default: "02",
  },
  {
    key: "projects.section.composition.index",
    page: "projects",
    label: "Section number: composition",
    default: "03",
  },
  {
    key: "projects.section.table.index",
    page: "projects",
    label: "Section number: full file",
    default: "04",
  },
  {
    key: "projects.stat.hint.months",
    page: "projects",
    label: "Stat hint: project months",
    default: "{count} months of project work since 2018",
    hint: "Token: {count}, counted from the project data.",
  },
  {
    key: "projects.stat.hint.onHold",
    page: "projects",
    label: "Stat hint: projects on hold",
    default: "{count} on hold waiting on business priorities",
    hint: "Token: {count}.",
  },
  {
    key: "projects.stat.hint.sites",
    page: "projects",
    label: "Stat hint: spread",
    default: "Projects across stores, warehouses, or cities",
  },
  {
    key: "projects.stat.hint.peakImpact",
    page: "projects",
    label: "Stat hint: highest impact",
    default: "Highest: {value} ({name})",
    hint: "Tokens: {value} and {name}.",
  },
  {
    key: "projects.stat.hint.noImpact",
    page: "projects",
    label: "Stat hint: no projects yet",
    default: "No projects recorded yet",
  },
  {
    key: "projects.chart.map.title",
    page: "projects",
    label: "Project map chart title",
    default: "Project map 2018 to 2025",
  },
  {
    key: "projects.chart.map.note",
    page: "projects",
    label: "Project map chart note",
    default: "The horizontal axis is time, the vertical axis is the kind of work.",
    multiline: true,
  },
  {
    key: "projects.chart.budget.title",
    page: "projects",
    label: "Budget per year chart title",
    default: "Budget and impact per year",
  },
  {
    key: "projects.chart.budget.note",
    page: "projects",
    label: "Budget per year chart note",
    default:
      "Bars are total budget in millions of rupiah, the dashed line is the average impact score for that same year.",
    multiline: true,
  },
  {
    key: "projects.chart.spread.title",
    page: "projects",
    label: "Year spread chart title",
    default: "Spread across years",
  },
  {
    key: "projects.chart.budget.legend.budget",
    page: "projects",
    label: "Budget chart legend: budget",
    default: "Budget",
  },
  {
    key: "projects.chart.budget.legend.impact",
    page: "projects",
    label: "Budget chart legend: average impact",
    default: "Average impact",
  },
  {
    key: "projects.chart.spread.note",
    page: "projects",
    label: "Kind spread chart note",
    default: "A compact bar: number of projects per year along with their budgets.",
    multiline: true,
  },
  {
    key: "projects.chart.spread.value",
    page: "projects",
    label: "Kind spread chart bar label",
    default: "{count} projects · Rp {amount}m",
    hint: "Tokens: {count} and {amount}.",
  },
  {
    key: "projects.chart.spread.aria",
    page: "projects",
    label: "Kind spread chart bar aria label",
    default: "{count} projects in {year}",
    hint: "Tokens: {count} and {year}.",
  },
  {
    key: "projects.chart.scatter.title",
    page: "projects",
    label: "Scatter chart title",
    default: "Budget against impact, per project",
  },
  {
    key: "projects.chart.scatter.note",
    page: "projects",
    label: "Scatter chart note",
    default:
      "Bubble size is the number of people involved. Projects with no direct budget (zero) are not drawn here, so no point is misleading.",
    multiline: true,
  },
  {
    key: "projects.composition.note",
    page: "projects",
    label: "Composition section note",
    default:
      "The two charts below use the same data from different angles, so the claims about where I focus can be checked.",
    multiline: true,
  },
  {
    key: "projects.composition.kinds.title",
    page: "projects",
    label: "Composition list heading",
    default: "Spread across kinds of work",
  },
  {
    key: "projects.composition.kinds.subtitle",
    page: "projects",
    label: "Composition list subtitle",
    default: "Number of projects and total budget per kind",
  },
  {
    key: "projects.composition.kinds.count",
    page: "projects",
    label: "Composition list: project count",
    default: "{count} projects",
    hint: "Token: {count}.",
  },
  {
    key: "projects.composition.kinds.budget",
    page: "projects",
    label: "Composition list: budget",
    default: "Rp {amount}m",
    hint: "Token: {amount}.",
  },
  {
    key: "projects.hold.eyebrow",
    page: "projects",
    label: "Honesty note eyebrow",
    default: "honesty note",
  },
  {
    key: "projects.hold.title",
    page: "projects",
    label: "Honesty note heading",
    default: "One project on this page is on hold, and I show that as it is.",
    hint: "Only shown when at least one project is on hold.",
  },
  {
    key: "projects.hold.body",
    page: "projects",
    label: "Honesty note paragraph",
    default:
      "{names} stopped not because it failed technically, but because business priorities shifted. A portfolio that only shows wins actually hides the ability a lead uses most often: deciding what not to build.",
    multiline: true,
    hint: "Token: {names}, filled with the projects currently on hold.",
  },
  {
    key: "projects.cta.eyebrow",
    page: "projects",
    label: "Closing section eyebrow",
    default: "continued",
  },
  {
    key: "projects.cta.title",
    page: "projects",
    label: "Closing section heading",
    default: "A budget only makes sense when the evidence follows. The next section shows the certifications and skills that support the decisions above.",
  },
  {
    key: "projects.cta.body",
    page: "projects",
    label: "Closing section paragraph",
    default:
      "If the numbers here look too clean, ask me. I can walk through the trade-offs, the parts that slipped, and what I would do differently on the next rollout.",
    multiline: true,
  },
  {
    key: "projects.cta.point.data",
    page: "projects",
    label: "Closing point: sample data",
    default: "All project numbers come from sample data",
  },
  {
    key: "projects.cta.point.noHidden",
    page: "projects",
    label: "Closing point: nothing hidden",
    default: "No project is hidden",
  },
  {
    key: "projects.cta.button.credentials",
    page: "projects",
    label: "Closing button: credentials",
    default: "View credentials",
  },
  {
    key: "projects.cta.button.contact",
    page: "projects",
    label: "Closing button: contact",
    default: "Ask a question",
  },
  {
    key: "projects.card.featured",
    page: "projects",
    label: "Featured card badge",
    default: "featured",
  },
  {
    key: "projects.card.impact",
    page: "projects",
    label: "Featured card impact label",
    default: "impact {value}",
    hint: "Token: {value}.",
  },
  {
    key: "projects.card.open",
    page: "projects",
    label: "Featured card button",
    default: "Open details",
  },
  {
    key: "projects.detail.role",
    page: "projects",
    label: "Detail label: role",
    default: "Role",
  },
  {
    key: "projects.detail.duration",
    page: "projects",
    label: "Detail label: duration",
    default: "Duration",
  },
  {
    key: "projects.detail.teamSize",
    page: "projects",
    label: "Detail label: team size",
    default: "Team size",
  },
  {
    key: "projects.detail.budget",
    page: "projects",
    label: "Detail label: budget",
    default: "Budget",
  },
  {
    key: "projects.detail.impact",
    page: "projects",
    label: "Detail label: impact score",
    default: "Impact score",
  },
  {
    key: "projects.detail.impact.note",
    page: "projects",
    label: "Detail note under impact score",
    default: "This number comes from my own internal scoring rubric, not a third-party audit.",
    multiline: true,
  },
  {
    key: "projects.detail.team",
    page: "projects",
    label: "Detail footer: team size",
    default: "{count} people involved",
    hint: "Token: {count}.",
  },
  {
    key: "projects.detail.value.months",
    page: "projects",
    label: "Detail value: duration",
    default: "{count} months",
    hint: "Token: {count}.",
  },
  {
    key: "projects.detail.value.people",
    page: "projects",
    label: "Detail value: team size",
    default: "{count} people",
    hint: "Token: {count}.",
  },
  {
    key: "projects.detail.value.budget",
    page: "projects",
    label: "Detail value: budget",
    default: "Rp {amount}m",
    hint: "Token: {amount}.",
  },
  {
    key: "projects.detail.value.internal",
    page: "projects",
    label: "Detail value: internal budget",
    default: "internal",
    hint: "Shown when a project has no budget figure.",
  },
  {
    key: "projects.featured.skills.title",
    page: "projects",
    label: "Featured section skills heading",
    default: "The skills behind them",
  },
];
