/**
 * Skills page copy.
 */
import type { ContentEntry } from "./types";

export const SKILLS_CONTENT: ContentEntry[] = [
  {
    key: "skills.eyebrow",
    page: "skills",
    label: "Page eyebrow",
    default: "Skills File",
  },
  {
    key: "skills.title",
    page: "skills",
    label: "Page main heading",
    default: "Technical Competence & Leadership Skills",
  },
  {
    key: "skills.lead",
    page: "skills",
    label: "Page lead paragraph",
    default:
      "Not every row on this page stands as tall as the others, and that is deliberate. The rating numbers here come from me. Data that comes from a third-party registry is kept separate at the bottom so the two never blend.",
    multiline: true,
  },
  {
    key: "skills.stat.tracked",
    page: "skills",
    label: "Stat label: skills tracked",
    default: "Skills tracked",
  },
  {
    key: "skills.stat.rating",
    page: "skills",
    label: "Stat label: average rating",
    default: "Average rating",
  },
  {
    key: "skills.stat.longest",
    page: "skills",
    label: "Stat label: longest track record",
    default: "Longest track record",
  },
  {
    key: "skills.stat.evidence",
    page: "skills",
    label: "Stat label: evidence links",
    default: "Evidence links",
  },
  {
    key: "skills.spread.eyebrow",
    page: "skills",
    label: "Spread section eyebrow",
    default: "Spread",
  },
  {
    key: "skills.spread.title",
    page: "skills",
    label: "Spread section heading",
    default: "Where my claims are strong, and where the evidence is still thin",
  },
  {
    key: "skills.selfrating.eyebrow",
    page: "skills",
    label: "Self rating section eyebrow",
    default: "Self rating",
  },
  {
    key: "skills.selfrating.title",
    page: "skills",
    label: "Self rating section heading ({count} = number of skills)",
    default: "{count} skills, filtered by the kind of work",
  },
  {
    key: "skills.selfrating.description",
    page: "skills",
    label: "Self rating section description",
    default:
      "Each card shows the level, years of experience, last year used, and evidence links. Pick a category to narrow the view.",
    multiline: true,
  },
  {
    key: "skills.registry.eyebrow",
    page: "skills",
    label: "Registry section eyebrow",
    default: "Third-party registry",
  },
  {
    key: "skills.registry.title",
    page: "skills",
    label: "Registry section heading",
    default: "Verified skills, shown as they are",
  },
  {
    key: "skills.registry.description",
    page: "skills",
    label: "Registry section description",
    default:
      "This section pulls data from a public skill registry, not from my own rating. If the registry cannot be reached, the panel will say so plainly.",
    multiline: true,
  },

  // ------------------------------------------------------- chart tooltips
  {
    key: "skills.chart.radar.series.rating",
    page: "skills",
    label: "Radar chart: self rating series",
    default: "Self rating",
  },
  {
    key: "skills.chart.radar.series.evidence",
    page: "skills",
    label: "Radar chart: evidence series",
    default: "Evidence strength",
  },
  {
    key: "skills.chart.top.row.level",
    page: "skills",
    label: "Top skills chart: level label",
    default: "Level",
  },
  {
    key: "skills.chart.top.row.experience",
    page: "skills",
    label: "Top skills chart: experience label",
    default: "Experience",
  },
  {
    key: "skills.chart.top.row.lastUsed",
    page: "skills",
    label: "Top skills chart: last used label",
    default: "Last used",
  },
  {
    key: "skills.chart.top.row.evidence",
    page: "skills",
    label: "Top skills chart: project evidence label",
    default: "Project evidence",
  },
  {
    key: "skills.chart.value.score",
    page: "skills",
    label: "Chart: score value",
    default: "{value}/100",
    hint: "Token: {value}. Used by the radar and top skills charts.",
  },
  {
    key: "skills.chart.value.years",
    page: "skills",
    label: "Chart: years value",
    default: "{count} years",
    hint: "Token: {count}.",
  },
  {
    key: "skills.chart.value.items",
    page: "skills",
    label: "Chart: item count value",
    default: "{count} items",
    hint: "Token: {count}.",
  },
  {
    key: "skills.chart.stack.row.usedIn",
    page: "skills",
    label: "Stack usage chart: used in label",
    default: "Used in",
  },
  {
    key: "skills.chart.stack.value.projects",
    page: "skills",
    label: "Stack usage chart: project count value",
    default: "{count} projects",
    hint: "Token: {count}.",
  },
  {
    key: "skills.chart.spread.row.longest",
    page: "skills",
    label: "Experience spread chart: longest held label",
    default: "Longest held",
  },
  {
    key: "skills.chart.spread.row.count",
    page: "skills",
    label: "Experience spread chart: skill count label",
    default: "Skill count",
  },
  {
    key: "skills.intro.index",
    page: "skills",
    label: "Page index marker",
    default: "04",
  },
  {
    key: "skills.section.spread.index",
    page: "skills",
    label: "Section index: spread",
    default: "01",
  },
  {
    key: "skills.section.selfrating.index",
    page: "skills",
    label: "Section index: self rating",
    default: "02",
  },
  {
    key: "skills.section.registry.index",
    page: "skills",
    label: "Section index: registry",
    default: "03",
  },
  {
    key: "skills.stat.tracked.hint",
    page: "skills",
    label: "Stat hint: tracked skills",
    default: "{count} categories, from leadership to operations",
    hint: "Token: {count} is the number of categories.",
  },
  {
    key: "skills.stat.longest.hint",
    page: "skills",
    label: "Stat hint: longest held skill",
    default: "{name}, last used {year}",
    hint: "Tokens: {name}, {year}.",
  },
  {
    key: "skills.stat.hint.rating",
    page: "skills",
    label: "Stat hint: rating",
    default: "Self-rated, not the result of third-party testing",
  },
  {
    key: "skills.stat.hint.evidence",
    page: "skills",
    label: "Stat hint: evidence",
    default: "Pointing to projects, certificates, or roles",
  },
  {
    key: "skills.selfrating.note",
    page: "skills",
    label: "Self rating chart: description",
    default:
      "The first chart compares the self rating against the amount of evidence in each category. If those two lines sit far apart, it means I rate myself higher than the amount of work I can actually show.",
    multiline: true,
  },
  {
    key: "skills.chart.radar.title",
    page: "skills",
    label: "Radar chart: title",
    default: "Balance of claim and evidence per category",
  },
  {
    key: "skills.chart.radar.note",
    page: "skills",
    label: "Radar chart: note",
    default:
      "The rust line is the self rating, the dashed moss line is evidence strength normalized to the same scale.",
    multiline: true,
  },
  {
    key: "skills.chart.top.title",
    page: "skills",
    label: "Top skills chart: title",
    default: "Ten highest ratings",
  },
  {
    key: "skills.chart.top.note",
    page: "skills",
    label: "Top skills chart: note",
    default: "Bar colour marks the band: deep rust above 85, rust above 75, moss for the rest.",
    multiline: true,
  },
  {
    key: "skills.chart.top.legend.high",
    page: "skills",
    label: "Top skills chart: legend high band",
    default: "85 and above",
  },
  {
    key: "skills.chart.top.legend.mid",
    page: "skills",
    label: "Top skills chart: legend middle band",
    default: "75 to 84",
  },
  {
    key: "skills.chart.top.legend.low",
    page: "skills",
    label: "Top skills chart: legend low band",
    default: "below 75",
  },
  {
    key: "skills.chart.stack.title",
    page: "skills",
    label: "Stack usage chart: title",
    default: "Tools actually used in projects",
  },
  {
    key: "skills.chart.stack.note",
    page: "skills",
    label: "Stack usage chart: note",
    default:
      "Only tools that appear in at least two projects. One-off tools are left out, so this chart does not turn into a wish list.",
    multiline: true,
  },
  {
    key: "skills.chart.spread.title",
    page: "skills",
    label: "Experience spread chart: title",
    default: "Track record per category",
  },
  {
    key: "skills.chart.spread.note",
    page: "skills",
    label: "Experience spread chart: note",
    default:
      "The highest figure in each category, not the average. One person who has spent nine years in a single area still shows up.",
    multiline: true,
  },
  {
    key: "skills.registry.source",
    page: "skills",
    label: "Registry panel: source sentence",
    default: "The numbers below are read straight from the {site} API response on {stamp}, with no edits from me. Largest category right now: {category}.",
    multiline: true,
    hint: "Tokens: {site}, {stamp}, and {category}.",
  },
  {
    key: "skills.registry.refresh",
    page: "skills",
    label: "Registry panel: refresh button",
    default: "Refresh",
  },
  {
    key: "skills.registry.stat.entries",
    page: "skills",
    label: "Registry stat: entries read",
    default: "Entries read",
  },
  {
    key: "skills.registry.stat.ratio",
    page: "skills",
    label: "Registry stat: certified ratio",
    default: "Certified ratio",
  },
  {
    key: "skills.registry.stat.score",
    page: "skills",
    label: "Registry stat: average score",
    default: "Average score",
  },
  {
    key: "skills.registry.stat.trust",
    page: "skills",
    label: "Registry stat: average trust",
    default: "Average trust",
  },
  {
    key: "skills.registry.tainted",
    page: "skills",
    label: "Registry panel: flagged entries note",
    default:
      "{count} entries were flagged as problematic by the automated scanner. I do not filter them out, so you can see them as they are.",
    multiline: true,
    hint: "Token: {count} is the number of flagged entries.",
  },
  {
    key: "skills.entries.title",
    page: "skills",
    label: "Entry list: heading",
    default: "List of entries read",
  },
  {
    key: "skills.entries.value",
    page: "skills",
    label: "Entry list: entry count",
    default: "{count} entries",
    hint: "Token: {count}.",
  },
  {
    key: "skills.entries.footnote",
    page: "skills",
    label: "Entry list: footnote",
    default: "Showing the first 12 entries, sorted by certification score. The rest follow the same pattern.",
    multiline: true,
  },
  {
    key: "skills.cta.button",
    page: "skills",
    label: "Closing CTA button",
    default: "Get in touch",
  },
  {
    key: "skills.card.years",
    page: "skills",
    label: "Skill card: years held",
    default: "{count} yrs",
    hint: "Token: {count}.",
  },
  {
    key: "skills.card.lastUsed",
    page: "skills",
    label: "Skill card: last used",
    default: "last used {year}",
    hint: "Token: {year}.",
  },
  {
    key: "skills.card.evidence",
    page: "skills",
    label: "Skill card: evidence heading",
    default: "evidence",
  },
  {
    key: "skills.card.rating.label",
    page: "skills",
    label: "Skill card: rating accessible label",
    default: "Self rating for {name}: {value} out of 100",
    hint: "Tokens: {name}, {value}.",
  },
  {
    key: "skills.entry.flagged",
    page: "skills",
    label: "Registry entry: flagged badge",
    default: "flagged",
  },
  {
    key: "skills.entry.score.title",
    page: "skills",
    label: "Registry entry: score tooltip",
    default: "Certification score",
  },
  {
    key: "skills.entry.stars.title",
    page: "skills",
    label: "Registry entry: stars tooltip",
    default: "Repository stars",
  },
  {
    key: "skills.entry.forks.title",
    page: "skills",
    label: "Registry entry: forks tooltip",
    default: "Repository forks",
  },
  {
    key: "skills.registry.loading.title",
    page: "skills",
    label: "Registry panel: loading heading",
    default: "contacting registry",
  },
  {
    key: "skills.registry.loading.body",
    page: "skills",
    label: "Registry panel: loading paragraph",
    default:
      "Fetching the verified skill list from {site}. This page shows no numbers at all until the answer actually arrives.",
    multiline: true,
    hint: "Token: {site} is the registry host name.",
  },
  {
    key: "skills.registry.offline.title",
    page: "skills",
    label: "Registry panel: offline heading",
    default: "registry unreachable",
  },
  {
    key: "skills.registry.offline.lead",
    page: "skills",
    label: "Registry panel: offline headline",
    default: "Third-party data failed to load, so I left this section empty.",
  },
  {
    key: "skills.registry.offline.body",
    page: "skills",
    label: "Registry panel: offline paragraph",
    default:
      "Cause: {reason}. Last attempt {stamp}. I would rather show an empty panel than fill in verification numbers I never received.",
    multiline: true,
    hint: "Tokens: {reason}, {stamp}.",
  },
  {
    key: "skills.registry.offline.tryAgain",
    page: "skills",
    label: "Registry panel: retry button",
    default: "Try again",
  },
  {
    key: "skills.registry.offline.trying",
    page: "skills",
    label: "Registry panel: retry button while loading",
    default: "Contacting",
  },
  {
    key: "skills.registry.ok.title",
    page: "skills",
    label: "Registry panel: reachable heading",
    default: "registry reachable",
  },
  {
    key: "skills.registry.entries.value",
    page: "skills",
    label: "Entry list: entry count",
    default: "{count} entries",
    hint: "Token: {count}.",
  },
  {
    key: "skills.clarify.title",
    page: "skills",
    label: "Registry disclaimer heading",
    default: "One clarification so nobody misreads this",
  },
  {
    key: "skills.clarify.body",
    page: "skills",
    label: "Registry disclaimer paragraph",
    default:
      "tasteskill.dev is not a skill data API provider. The one with a real public API is the verified-skill.com registry, and that is what I call. If you go looking for a person profile on tasteskill.dev, you will not find one.",
    multiline: true,
  },
  {
    key: "skills.map.eyebrow",
    page: "skills",
    label: "Competency map: eyebrow",
    default: "translation",
  },
  {
    key: "skills.map.title",
    page: "skills",
    label: "Competency map: heading",
    default: "Four areas of work I connect to the registry results",
  },
  {
    key: "skills.map.body",
    page: "skills",
    label: "Competency map: paragraph",
    default:
      "I wrote this mapping myself. The registry does not know what I do day to day, so the links below are my own translation, not an automatic claim from any system.",
    multiline: true,
  },
  {
    key: "skills.summary.title",
    page: "skills",
    label: "Category summary: heading",
    default: "Summary per category",
  },
  {
    key: "skills.summary.note",
    page: "skills",
    label: "Category summary: note",
    default: "Sorted by highest average rating",
  },
  {
    key: "skills.summary.row",
    page: "skills",
    label: "Category summary: row detail",
    default: "{count} skills · {evidence} evidence links · longest {years} yrs",
    hint: "Tokens: {count}, {evidence}, {years}.",
  },
  {
    key: "skills.summary.row.aria",
    page: "skills",
    label: "Category summary: progress accessible label",
    default: "Average {category}: {value} out of 100",
    hint: "Tokens: {category}, {value}.",
  },
  {
    key: "skills.cta.eyebrow",
    page: "skills",
    label: "Closing CTA eyebrow",
    default: "continued",
  },
  {
    key: "skills.cta.body",
    page: "skills",
    label: "Closing CTA paragraph",
    default:
      "A skill without context is just a list of words. How I make decisions lives on the about page.",
    multiline: true,
  },
  {
    key: "skills.cta.point.apart",
    page: "skills",
    label: "Closing CTA point: self ratings kept apart",
    default: "Self ratings and registry numbers kept apart",
  },
  {
    key: "skills.cta.point.offline",
    page: "skills",
    label: "Closing CTA point: registry failure",
    default: "Registry failure means an empty panel",
  },
  {
    key: "skills.cta.button.about",
    page: "skills",
    label: "Closing CTA button: about",
    default: "Read the working principles",
  },
  {
    key: "skills.toggle.all",
    page: "skills",
    label: "Category filter: all tab",
    default: "All ({count})",
    hint: "Token: {count}.",
  },
  {
    key: "skills.honesty.eyebrow",
    page: "skills",
    label: "Honesty note: eyebrow",
    default: "honesty note",
  },
  {
    key: "skills.honesty.title",
    page: "skills",
    label: "Honesty note: heading",
    default: "Two things on this page stop me from claiming I have mastered all of it.",
  },
  {
    key: "skills.honesty.stale.title",
    page: "skills",
    label: "Honesty note: rarely used heading",
    default: "rarely used",
  },
  {
    key: "skills.honesty.stale.body",
    page: "skills",
    label: "Honesty note: rarely used paragraph",
    default:
      "{count} skills were last used in {year}. I still consider all of them alive, but calling them \"currently active\" would be a stretch.",
    multiline: true,
    hint: "Tokens: {count}, {year}.",
  },
  {
    key: "skills.honesty.thin.title",
    page: "skills",
    label: "Honesty note: thin evidence heading",
    default: "thin evidence",
  },
  {
    key: "skills.honesty.thin.body",
    page: "skills",
    label: "Honesty note: thin evidence paragraph",
    default:
      "{count} skills I rate 80 or above, yet they only have one evidence link. High claim, short trail, and I show that as it is.",
    multiline: true,
    hint: "Token: {count}.",
  },
  {
    key: "skills.honesty.footnote",
    page: "skills",
    label: "Honesty note: closing footnote",
    default:
      "I deliberately did not inflate the ratings for skills with thin evidence. A portfolio where every bar is full gives you no information at all.",
    multiline: true,
  },
];
